'use strict';
/**
 * the config of the asiainfo project list
 *
 * @author: yunzhi li
 * @version: 2016/10/8 15:16
 *           $Id$
 */

export default {
    'pro': [
        {
            sn: '2016-PI001',
            name: 'init',
            title: '框架初始化样例项目',
            type: 'web',
            dev: 'pc',
            date: '2016-11-21',
            remUnit: 20,
            compileCss: 'css',
            svn: ''
        }, {
            sn: '2016-SN12',
            name: 'gqkuandai',
            title: '陕西宽带国庆活动',
            type: 'web',
            dev: 'pc',
            date: '2016-10-09',
            remUnit: 20,
            svn: ''
        }, {
            sn: '2016-SN03',
            name: 'sxwt',
            title: '陕西网厅客户关怀平台',
            type: 'web',
            dev: 'pc',
            date: '2016-09-18',
            remUnit: 20,
            svn: ''
        }, {
            sn: '2016-HN004',
            name: 'gqliuliang',
            title: '国庆流量包月促销活动页',
            type: 'wap',
            dev: 'phone',
            date: '2016-10-09',
            remUnit: 20,
            svn: ''
        }, {
            sn: '2016-SN12-1',
            name: 'gqkuandai01',
            title: '国庆宽带活动页-节后阶段',
            type: 'web',
            dev: 'pc',
            date: '2016-10-11',
            remUnit: 20,
            svn: ''
        }, {
            sn: '2016-SN013',
            name: 'saomalogin',
            title: '网厅二维码扫码登录',
            type: 'web',
            dev: 'pc',
            date: '2016-10-13',
            remUnit: 20,
            svn: ''
        }, {
            sn: '2016-QH001',
            name: 'qhcmcpay',
            title: '青海移动-支付页面',
            type: 'web',
            dev: 'phone',
            date: '2016-10-19',
            remUnit: 45,
            svn: ''
        }, {
            sn: '2016-HN012',
            name: 'kanjia',
            title: '湖南移动-拉帮结派放肆砍',
            type: 'wap',
            dev: 'phone',
            date: '2016-10-26',
            remUnit: 75,
            svn: ''
        }, {
            sn: '2016-PP001',
            name: 'gongwu',
            title: '共武文化',
            type: 'web',
            dev: 'pc',
            date: '2016-10-19',
            remUnit: 20,
            svn: ''
        }, {
            sn: '2016-PP002',
            name: 'sanxiangdl',
            title: '三湘电力',
            type: 'web',
            dev: 'pc',
            date: '2016-10-24',
            remUnit: 20,
            svn: ''
        }, {
            sn: '2016-PP003',
            name: 'msnui',
            title: 'msnui',
            type: 'web',
            dev: 'pc',
            date: '2016-11-04',
            remUnit: 20,
            svn: ''
        }, {
            sn: '2016-PP004',
            name: 'hqmmw',
            title: '环球苗木网',
            type: 'wap',
            dev: 'phone',
            date: '2016-11-05',
            remUnit: 75,
            svn: ''
        }, {
            sn: '2016-PP005',
            name: 'sxdl',
            title: '湖南三湘电缆',
            type: 'wap',
            dev: 'phone',
            date: '2016-12-12',
            remUnit: 75,
            // less\css\sass\postcss
            // 当前仍只支持前两种
            compileCss: 'less',
            svn: ''
        }, {
            sn: '2016-HN020',
            name: 'qudaojz',
            title: '湖南渠道集中化平台',
            type: 'web',
            dev: 'phone',
            date: '2016-11-11',
            remUnit: 192,
            svn: ''
        }, {
            sn: '2016-HN026',
            name: 'guodanian',
            title: '湖南移动-过大年聚合页',
            type: 'web',
            dev: 'pc',
            date: '2016-11-30',
            remUnit: 75,
            // less\css\sass\postcss
            // 当前仍只支持前两种
            compileCss: 'less',
            svn: ''
        }, {
            sn: '2016-HN034',
            name: 'lakanjia',
            title: '湖南移动-呼朋唤友来砍价',
            type: 'wap',
            dev: 'phone',
            date: '2016-12-07',
            remUnit: 75,
            // less\css\sass\postcss
            // 当前仍只支持前两种
            compileCss: 'less',
            svn: ''
        }
    ]
}


